**1.3.1 Задание**

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [12]:
#1.3.1 Задание

import numpy as np
X = np.zeros((4,4))
X[1::2,0::2] = 1
X[0::2,1::2] = 1
print(X)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


**1.3.2 Задание**

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange. 

In [13]:
#1.3.2 Задание

X = np.zeros((5,5))
X += np.arange(5)
print(X)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


**1.3.3 Задание**

Создать массив 3x3x3 со случайными значениями. 

In [14]:
#1.3.3 Задание

X = np.random.random((3,3,3))
print(X)

[[[0.892475   0.32607043 0.12072027]
  [0.26120851 0.18108654 0.95247288]
  [0.81129011 0.77459383 0.98575171]]

 [[0.40726082 0.04845638 0.13294155]
  [0.70604003 0.08903553 0.00218179]
  [0.46823072 0.21793697 0.67746437]]

 [[0.96411109 0.13383035 0.56091142]
  [0.67573287 0.23117439 0.58757336]
  [0.70045872 0.15755289 0.34454844]]]


**1.3.4 Задание**

Создать матрицу с 0 внутри, и 1 на границах. 

In [15]:
#1.3.4 Задание

X = np.ones((5, 5))
X[1:-1, 1:-1] = 0
print(X)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**1.3.5 Задание**

Создайте массив и отсортируйте его по убыванию. 

In [16]:
#1.3.5 Задание

X = np.arange(1, 10)
print(np.sort(X)[::-1])

[9 8 7 6 5 4 3 2 1]


**1.3.6 Задание**

Создайте матрицу, выведите ее форму, размер и размерность. 

In [17]:
#1.3.6 Задание

X = int(input('Введите количество строк:'))
Y = int(input('Введите количество столбцов:'))
Z = np.zeros((X, Y), int)
print(Z)
print(np.shape(Z))
print(np.size(Z))
print(np.ndim(Z))


[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
(5, 5)
25
2


**2.3.1 Задание**

Найдите евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу. 

In [ ]:
#2.3.1 Задание

a = np.array((3, 0, 3))
b = np.array((3, 3, 3))

square = np.square(a - b)
sum_square = np.sum(square)

distance = np.sqrt(sum_square)
print(distance)

3.0


**2.3.2 Задание**

Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных (например, коллекцию фреймов данных можно найти здесь: https://github.com/akmand/datasets). 

In [ ]:
#2.3.2 Задание
import pandas as pd
url='https://raw.githubusercontent.com/akmand/datasets/main/abolone.csv'
dataframe=pd.read_csv(url)
dataframe.head(7)

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   
5      I   0.425     0.300   0.095        0.3515          0.1410   
6      F   0.530     0.415   0.150        0.7775          0.2370   

   Viscera weight  Shell weight  Rings  
0          0.1010         0.150     15  
1          0.0485         0.070      7  
2          0.1415         0.210      9  
3          0.1140         0.155     10  
4          0.0395         0.055      7  
5          0.0775         0.120      8  
6          0.1415         0.330     20

**2.3.3 Задание**

Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7. 

In [ ]:
#2.3.3 Задание

url='https://raw.githubusercontent.com/akmand/datasets/main/abolone.csv'

dataframe=pd.read_csv(url)
dataframe.head(10)
dataframe.tail(3)
dataframe.shape
dataframe.describe()
dataframe.iloc[1:4]
dataframe[dataframe['Gender'] == 'M'].head(5)

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
0       M   0.455     0.365   0.095        0.5140          0.2245   
1       M   0.350     0.265   0.090        0.2255          0.0995   
3       M   0.440     0.365   0.125        0.5160          0.2155   
8       M   0.475     0.370   0.125        0.5095          0.2165   
11      M   0.430     0.350   0.110        0.4060          0.1675   

    Viscera weight  Shell weight  Rings  
0           0.1010         0.150     15  
1           0.0485         0.070      7  
3           0.1140         0.155     10  
8           0.1125         0.165      9  
11          0.0810         0.135     10

**3.3.2 Задание**

Загрузить фрейм данных по ссылке: https://raw.githubusercontent.com/akmand/datasets/master/iris.csv. Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования. 

In [25]:
#3.3.2 Задание

from sklearn.preprocessing import StandardScaler, MinMaxScaler
dataframe = pd.read_csv('https://raw.githubusercontent.com/akmand/datasets/master/iris.csv')

dataframe[['sepal_length_cm']] = MinMaxScaler().fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']] = StandardScaler().fit_transform(dataframe[['sepal_width_cm']])
dataframe


sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]